# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Creative portfolio"
license = "MIT"
licenselink = "https://github.com/kishaningithub/hugo-creative-portfolio-theme/blob/master/LICENSE"
description = "theme for the Media Archaeology Lab merch website"
homepage = "https://github.com/kishaningithub/hugo-creative-portfolio-theme"
categories = ["merch"]
tags = ["apparel", "portfolio", "misc", "accessories", "responsive"]
features = ["disqus", "bootstrap", "responsive", "google analytics"]
min_version = 0.20



# If porting an existing theme
[original]
  name = "bootstrapious"
  homepage = "https://bootstrapious.com/p/creative-portfolio"
